version: "3.9"

services:
  dind:
    image: docker:20.10-dind
    container_name: dind
    hostname: docker                  # matches DOCKER_HOST= tcp://docker:2376
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    networks: [jenkins]
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - dind-storage:/var/lib/docker
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    user: root
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: "1"
    networks: [jenkins]
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - docker-certs-client:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    restart: unless-stopped

volumes:
  docker-certs-ca:
  docker-certs-client:
  jenkins-data:
  dind-storage:

networks:
  jenkins:

