version: '3.9'

services:
  dind:                               # Docker-in-Docker service
    image: docker:dind
    container_name: dind
    privileged: true                  # It must enable privileged mode to run Docker
    networks:
      - jenkins
    environment:
      DOCKER_TLS_CERTDIR: /certs      # Docker TLS Certificate Directory
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - jenkins-data:/var/jenkins_home # Jenkins volumes
    restart: unless-stopped

  jenkins:                            # Jenkins service
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    user: root                        # Requires root to call Docker
    networks:
      - jenkins
    environment:
      DOCKER_HOST: "tcp://docker:2376"  # Let Jenkins execute Docker through dind
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    ports:
      - "8080:8080"                   # Jenkins Web interface
      - "50000:50000"                 # Jenkins Agent port
    volumes:
      - docker-certs-client:/certs/client:ro
      - jenkins-data:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker  # Install the host Docker CLI
    restart: unless-stopped

volumes:
  docker-certs-ca:
  docker-certs-client:
  jenkins-data:

networks:
  jenkins:
